version: '3.8'
services:
  vision_db:
    build:
      context: ./Docker-files/db
    image: kalai25/devdb
    container_name: vision_db
    ports:
      - "3306:3306"
    volumes:
      - vision_dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vision_dbpass

  vision_cache01:
    image: memcached
    ports:
      - "11211:11211"

  vision_mq01:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vision_app:
    build:
      context: ./Docker-files/app
    image: kalai25/devapp:0.1
    container_name: vision_app
    ports:
      - "8080:8080"
    volumes:
      - vision_appdata:/usr/local/tomcat/webapps

  vision_web:
    build:
      context: ./Docker-files/web
    image: kalai25/devweb
    container_name: vision_web
    ports:
      - "80:80"

volumes:
   vision_dbdata: {}
   vision_appdata: {}
